# Generated by Django 6.0.9 on 2026-10-08 09:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bloc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Ex. : A, B, C…", max_length=10, unique=True
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        blank=True,
                        help_text="Ex. : Pièces moteur, Ciment…",
                        max_length=100,
                    ),
                ),
                (
                    "couleur",
                    models.CharField(
                        default="#3b82f6",
                        help_text="Couleur dans la vue 3D (#rrggbb).",
                        max_length=7,
                    ),
                ),
                (
                    "x",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=7,
                        verbose_name="position X (m)",
                    ),
                ),
                (
                    "z",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=7,
                        verbose_name="position Z (m)",
                    ),
                ),
                (
                    "largeur",
                    models.DecimalField(
                        decimal_places=2,
                        default=10,
                        max_digits=7,
                        verbose_name="largeur (m)",
                    ),
                ),
                (
                    "profondeur",
                    models.DecimalField(
                        decimal_places=2,
                        default=8,
                        max_digits=7,
                        verbose_name="profondeur (m)",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "catégorie",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Chantier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150, unique=True)),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Engin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "designation",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="désignation"
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150, unique=True)),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="téléphone"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("adresse", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="BonSortie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=30,
                        unique=True,
                        verbose_name="numéro",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("VALIDE", "Validé"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="BROUILLON",
                        editable=False,
                        max_length=10,
                    ),
                ),
                ("observation", models.TextField(blank=True)),
                ("date_validation", models.DateTimeField(editable=False, null=True)),
                ("demandeur", models.CharField(max_length=150)),
                (
                    "cree_par",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="validé par",
                    ),
                ),
                (
                    "chantier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stock.chantier"
                    ),
                ),
                (
                    "engin",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facultatif : engin ou camion destinataire.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stock.engin",
                    ),
                ),
            ],
            options={
                "verbose_name": "bon de sortie",
                "verbose_name_plural": "bons de sortie",
                "ordering": ["-date", "-id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Etagere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(help_text="Ex. : R1, E03…", max_length=20)),
                (
                    "x",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=7,
                        verbose_name="position X dans le bloc (m)",
                    ),
                ),
                (
                    "z",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=7,
                        verbose_name="position Z dans le bloc (m)",
                    ),
                ),
                (
                    "largeur",
                    models.DecimalField(
                        decimal_places=2,
                        default=3,
                        max_digits=6,
                        verbose_name="largeur (m)",
                    ),
                ),
                (
                    "profondeur",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=6,
                        verbose_name="profondeur (m)",
                    ),
                ),
                (
                    "hauteur",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.5,
                        max_digits=6,
                        verbose_name="hauteur (m)",
                    ),
                ),
                (
                    "nb_niveaux",
                    models.PositiveSmallIntegerField(
                        default=4, verbose_name="nombre de niveaux"
                    ),
                ),
                (
                    "tournee",
                    models.BooleanField(default=False, verbose_name="tournée de 90°"),
                ),
                (
                    "bloc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etageres",
                        to="stock.bloc",
                    ),
                ),
            ],
            options={
                "verbose_name": "étagère",
                "ordering": ["bloc__code", "code"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "designation",
                    models.CharField(max_length=200, verbose_name="désignation"),
                ),
                (
                    "unite",
                    models.CharField(
                        choices=[
                            ("U", "Unité"),
                            ("KG", "Kilogramme"),
                            ("T", "Tonne"),
                            ("L", "Litre"),
                            ("M", "Mètre"),
                            ("M2", "Mètre carré"),
                            ("M3", "Mètre cube"),
                            ("SAC", "Sac"),
                            ("FUT", "Fût"),
                            ("BID", "Bidon"),
                            ("BOITE", "Boîte"),
                            ("JEU", "Jeu"),
                            ("ROUL", "Rouleau"),
                        ],
                        default="U",
                        max_length=10,
                        verbose_name="unité",
                    ),
                ),
                (
                    "niveau",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="1 = niveau du bas.", null=True
                    ),
                ),
                (
                    "case",
                    models.CharField(
                        blank=True,
                        help_text="Précision facultative : case, bac, côté…",
                        max_length=30,
                    ),
                ),
                (
                    "reference_fabricant",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="référence fabricant"
                    ),
                ),
                (
                    "mots_cles",
                    models.CharField(
                        blank=True,
                        help_text="Autres noms utilisés au magasin (français, darija…), séparés par des virgules.",
                        max_length=255,
                        verbose_name="mots-clés",
                    ),
                ),
                ("photo", models.ImageField(blank=True, upload_to="articles/")),
                (
                    "stock_min",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Une alerte s'affiche quand le stock atteint ce seuil.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="stock minimum",
                    ),
                ),
                (
                    "stock",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        editable=False,
                        max_digits=14,
                        verbose_name="stock actuel",
                    ),
                ),
                (
                    "prix_moyen",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=16,
                        verbose_name="prix moyen pondéré",
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stock.categorie",
                        verbose_name="catégorie",
                    ),
                ),
                (
                    "etagere",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="stock.etagere",
                        verbose_name="étagère",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="BonEntree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=30,
                        unique=True,
                        verbose_name="numéro",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("VALIDE", "Validé"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="BROUILLON",
                        editable=False,
                        max_length=10,
                    ),
                ),
                ("observation", models.TextField(blank=True)),
                ("date_validation", models.DateTimeField(editable=False, null=True)),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="réf. BL / facture"
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="validé par",
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stock.fournisseur",
                    ),
                ),
            ],
            options={
                "verbose_name": "bon d'entrée",
                "verbose_name_plural": "bons d'entrée",
                "ordering": ["-date", "-id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Inventaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=30,
                        unique=True,
                        verbose_name="numéro",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("VALIDE", "Validé"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="BROUILLON",
                        editable=False,
                        max_length=10,
                    ),
                ),
                ("observation", models.TextField(blank=True)),
                ("date_validation", models.DateTimeField(editable=False, null=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="validé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "inventaire",
                "ordering": ["-date", "-id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LigneEntree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="quantité",
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="prix unitaire",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stock.article"
                    ),
                ),
                (
                    "bon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="stock.bonentree",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne",
            },
        ),
        migrations.CreateModel(
            name="LigneInventaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock_compte",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="stock compté",
                    ),
                ),
                (
                    "stock_theorique",
                    models.DecimalField(
                        decimal_places=3,
                        editable=False,
                        max_digits=14,
                        null=True,
                        verbose_name="stock théorique",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stock.article"
                    ),
                ),
                (
                    "bon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="stock.inventaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne",
            },
        ),
        migrations.CreateModel(
            name="LigneSortie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="quantité",
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=16,
                        verbose_name="prix unitaire",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stock.article"
                    ),
                ),
                (
                    "bon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="stock.bonsortie",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne",
            },
        ),
        migrations.CreateModel(
            name="MouvementStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ENTREE", "Entrée"),
                            ("SORTIE", "Sortie"),
                            ("INVENTAIRE", "Ajustement d'inventaire"),
                            ("ANNULATION", "Annulation"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "quantite",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Positive en entrée, négative en sortie.",
                        max_digits=14,
                        verbose_name="quantité",
                    ),
                ),
                (
                    "stock_apres",
                    models.DecimalField(
                        decimal_places=3, max_digits=14, verbose_name="stock après"
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="prix unitaire",
                    ),
                ),
                ("reference", models.CharField(max_length=30, verbose_name="bon")),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mouvements",
                        to="stock.article",
                    ),
                ),
                (
                    "chantier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stock.chantier",
                    ),
                ),
                (
                    "engin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stock.engin",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "mouvement de stock",
                "verbose_name_plural": "mouvements de stock",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="etagere",
            constraint=models.UniqueConstraint(
                fields=("bloc", "code"), name="etagere_unique_par_bloc"
            ),
        ),
        migrations.AddConstraint(
            model_name="ligneinventaire",
            constraint=models.UniqueConstraint(
                fields=("bon", "article"), name="inventaire_article_unique"
            ),
        ),
    ]
