# Generated by Django 6.0.9 on 2026-10-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parametres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_societe",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="nom de la société"
                    ),
                ),
                ("logo", models.ImageField(blank=True, upload_to="societe/")),
                (
                    "couleur",
                    models.CharField(
                        default="#2457d6",
                        max_length=7,
                        verbose_name="couleur principale",
                    ),
                ),
                ("adresse", models.CharField(blank=True, max_length=255)),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="téléphone"
                    ),
                ),
                ("devise", models.CharField(default="FCFA", max_length=10)),
                (
                    "signataire",
                    models.CharField(
                        default="Le magasinier",
                        help_text="Texte sous la case de signature, sur les bons imprimés.",
                        max_length=100,
                        verbose_name="signature des bons",
                    ),
                ),
            ],
            options={
                "verbose_name": "paramètres de la société",
                "verbose_name_plural": "paramètres de la société",
            },
        ),
    ]
