# Generated by Django 6.0.9 on 2026-10-08 12:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_parametres"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x1", models.DecimalField(decimal_places=2, max_digits=7)),
                ("z1", models.DecimalField(decimal_places=2, max_digits=7)),
                ("x2", models.DecimalField(decimal_places=2, max_digits=7)),
                ("z2", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "epaisseur",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.20"),
                        max_digits=4,
                        verbose_name="épaisseur (m)",
                    ),
                ),
                (
                    "hauteur",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("3.00"),
                        max_digits=5,
                        verbose_name="hauteur (m)",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
