# Generated by Django 6.0.9 on 2026-10-08 12:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_murs"),
    ]

    operations = [
        migrations.CreateModel(
            name="Element",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=20)),
                ("nom", models.CharField(blank=True, max_length=60)),
                ("x", models.DecimalField(decimal_places=2, max_digits=7)),
                ("z", models.DecimalField(decimal_places=2, max_digits=7)),
                ("largeur", models.DecimalField(decimal_places=2, max_digits=6)),
                ("profondeur", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "hauteur",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "rotation",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                ("couleur", models.CharField(default="#64748b", max_length=7)),
            ],
            options={
                "verbose_name": "élément du plan",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="mur",
            name="couleur",
            field=models.CharField(default="#d6d3d1", max_length=7),
        ),
    ]
