# Generated by Django 6.0.9 on 2026-10-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_elements_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametres",
            name="cle_licence",
            field=models.TextField(blank=True, verbose_name="clé d'activation"),
        ),
        migrations.AddField(
            model_name="parametres",
            name="debut_essai",
            field=models.DateField(
                blank=True, null=True, verbose_name="début de l'essai"
            ),
        ),
    ]
