# Generated by Django 6.0.9 on 2026-10-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0005_licence"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametres",
            name="masquer_prix_sortie",
            field=models.BooleanField(
                default=False,
                verbose_name="Ne pas imprimer les prix sur les bons de sortie",
            ),
        ),
        migrations.AddField(
            model_name="parametres",
            name="ncc",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="N° compte contribuable (NCC)"
            ),
        ),
        migrations.AddField(
            model_name="parametres",
            name="rccm",
            field=models.CharField(
                blank=True,
                help_text="N° du registre du commerce, imprimé en haut des bons.",
                max_length=60,
                verbose_name="RCCM",
            ),
        ),
    ]
