# Generated by Django 6.0.9 on 2026-10-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0005_licence"),
    ]

    operations = [
        migrations.AddField(
            model_name="bonentree",
            name="jeton",
            field=models.CharField(
                blank=True, editable=False, max_length=32, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="bonsortie",
            name="jeton",
            field=models.CharField(
                blank=True, editable=False, max_length=32, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="inventaire",
            name="jeton",
            field=models.CharField(
                blank=True, editable=False, max_length=32, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="unite",
            field=models.CharField(
                choices=[
                    ("U", "Unité"),
                    ("KG", "Kilogramme"),
                    ("T", "Tonne"),
                    ("L", "Litre"),
                    ("M", "Mètre"),
                    ("M2", "Mètre carré"),
                    ("M3", "Mètre cube"),
                    ("SAC", "Sac"),
                    ("FUT", "Fût"),
                    ("BID", "Bidon"),
                    ("BOITE", "Boîte"),
                    ("JEU", "Jeu"),
                    ("ROUL", "Rouleau"),
                    ("PAIRE", "Paire"),
                    ("CARTON", "Carton"),
                    ("PAQ", "Paquet"),
                    ("BARRE", "Barre"),
                    ("LOT", "Lot"),
                    ("FEUILLE", "Feuille"),
                ],
                default="U",
                max_length=10,
                verbose_name="unité",
            ),
        ),
    ]
