# Generated by Django 6.0.9 on 2026-10-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0006_parametres_rccm_ncc_prix_sortie"),
        ("stock", "0006_unites_btp_et_jeton_anti_double_envoi"),
    ]

    operations = []
